### PR TITLE
feat: bump Rspack / Rsbuild to v1

### PR DESCRIPTION
**Pull request by chenjiahan**
Bump Rspack / Rsbuild to v1.

Updated stats in M1 pro:

image

### CODE REVIEW

**Comment by chenjiahan** [comment]
@ErKeLost PTAL❤️  Thanks!

**Comment by ErKeLost** [comment]
@chenjiahan  ok I'll update the version of the data and other tools

**Comment by ErKeLost** [comment]
The data I recompiled after updating the farm version is on my m1 pro

image

**Comment by chenjiahan** [comment]
Thank you!

**Comment by ErKeLost** [comment]
The latest data has been updated
https://github.com/farm-fe/performance-compare?tab=readme-ov-file#performance-compare

**Pull request merged**
